/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Epilogue } from "@next/font/google";
import Navbar from "@/components/UI/Navbar";
import Image from "next/image";

const epilogue = Epilogue({ subsets: ["latin"] });

const clients = [
  "/assets/client-databiz.svg",
  "/assets/client-audiophile.svg",
  "/assets/client-meet.svg",
  "/assets/client-maker.svg",
];

export default function Home() {
  const test = () => {};
  return (
    <>
      <Head>
        <title>Snap - Intro section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main className={`` + epilogue.className}>
        <Navbar />

        <section className="mobile:px-4">
          <Image
            src={"/assets/image-hero-mobile.png"}
            alt="Hero"
            width={375}
            height={281.25}
            className="mx-auto mt-2"
          />
        </section>

        <section className="mt-4 flex-col items-center justify-center">
          <h1 className="text-center text-4xl font-bold">Make remote work</h1>
          <p className="mt-4 px-4 text-center text-gray-500">
            Get your team in sync, no matter your location. Streamline
            processes, create team rituals, and watch productivity soar.
          </p>

          <button className="mx-auto mt-6 block rounded-xl bg-black px-5 py-3 font-semibold text-white">
            Learn more
          </button>
        </section>

        <section className="flex mt-6 px-2 items-center justify-evenly">
          {clients.map((client, i) => (
            <img className="w-[4.5rem] h-auto" key={`client-${i}`} src={client} alt={`Client ${i + 1}`} />
          ))}
        </section>
      </main>
    </>
  );
}
